import SwiftUI

// MARK: - MultimodalNoteView

/// Renders StructuredNotes with inline images and section navigation.
/// TODO: Phase 3 — Full markdown rendering, image loading from ImageStore
struct MultimodalNoteView: View {
    let notes: StructuredNotes

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Title
            Text(notes.title)
                .font(.title)
                .fontWeight(.bold)
                .foregroundColor(NoteVConfig.Design.textPrimary)

            // Summary
            if !notes.summary.isEmpty {
                Text(notes.summary)
                    .font(.body)
                    .foregroundColor(NoteVConfig.Design.textSecondary)
                    .padding()
                    .background(NoteVConfig.Design.surface)
                    .cornerRadius(NoteVConfig.Design.cornerRadius)
            }

            // Key Takeaways
            if !notes.keyTakeaways.isEmpty {
                VStack(alignment: .leading, spacing: 8) {
                    Text("Key Takeaways")
                        .font(.headline)
                        .foregroundColor(NoteVConfig.Design.accent)

                    ForEach(notes.keyTakeaways, id: \.self) { takeaway in
                        HStack(alignment: .top, spacing: 8) {
                            Image(systemName: "star.fill")
                                .font(.caption)
                                .foregroundColor(NoteVConfig.Design.accent)
                                .padding(.top, 3)

                            Text(takeaway)
                                .font(.body)
                                .foregroundColor(NoteVConfig.Design.textPrimary)
                        }
                    }
                }
                .padding()
                .background(NoteVConfig.Design.surface)
                .cornerRadius(NoteVConfig.Design.cornerRadius)
            }

            // Sections
            ForEach(notes.sections.sorted { $0.order < $1.order }) { section in
                VStack(alignment: .leading, spacing: 12) {
                    Text(section.title)
                        .font(.title2)
                        .fontWeight(.semibold)
                        .foregroundColor(NoteVConfig.Design.textPrimary)

                    Text(section.content)
                        .font(.body)
                        .foregroundColor(NoteVConfig.Design.textPrimary)
                        .lineSpacing(4)

                    // Section images
                    ForEach(section.images) { image in
                        VStack(spacing: 4) {
                            // TODO: Phase 3 — Load actual image from ImageStore
                            RoundedRectangle(cornerRadius: 8)
                                .fill(NoteVConfig.Design.surface)
                                .frame(height: 200)
                                .overlay(
                                    Image(systemName: "photo")
                                        .font(.largeTitle)
                                        .foregroundColor(NoteVConfig.Design.textSecondary)
                                )

                            if !image.caption.isEmpty {
                                Text(image.caption)
                                    .font(.caption)
                                    .foregroundColor(NoteVConfig.Design.textSecondary)
                                    .italic()
                            }
                        }
                    }
                }
            }

            // Generation info
            HStack {
                Spacer()
                Text("Generated by \(notes.modelUsed)")
                    .font(.caption2)
                    .foregroundColor(NoteVConfig.Design.textSecondary)
            }
            .padding(.top, 20)
        }
    }
}

// MARK: - Preview

#Preview {
    ScrollView {
        MultimodalNoteView(notes: StructuredNotes(
            title: "Sample Lecture Notes",
            summary: "This is a preview of generated notes.",
            sections: [
                NoteSection(title: "Introduction", content: "Sample content here...", order: 0)
            ],
            keyTakeaways: ["First key point", "Second key point"]
        ))
        .padding()
    }
    .background(NoteVConfig.Design.background)
}
