import Foundation

// MARK: - NoteImage

/// An image referenced within the generated notes.
struct NoteImage: Identifiable, Codable, Sendable {
    let id: UUID
    /// Filename of the image (references a stored frame)
    let filename: String
    /// Caption generated by the LLM
    let caption: String
    /// Timestamp in the session where this image was captured
    let timestamp: TimeInterval

    init(
        id: UUID = UUID(),
        filename: String,
        caption: String = "",
        timestamp: TimeInterval = 0
    ) {
        self.id = id
        self.filename = filename
        self.caption = caption
        self.timestamp = timestamp
    }
}

// MARK: - NoteSection

/// A section within the structured notes.
struct NoteSection: Identifiable, Codable, Sendable {
    let id: UUID
    /// Section heading
    let title: String
    /// Markdown-formatted content
    let content: String
    /// Images referenced in this section
    let images: [NoteImage]
    /// Order index for display
    let order: Int

    init(
        id: UUID = UUID(),
        title: String,
        content: String = "",
        images: [NoteImage] = [],
        order: Int = 0
    ) {
        self.id = id
        self.title = title
        self.content = content
        self.images = images
        self.order = order
    }
}

// MARK: - StructuredNotes

/// The final AI-generated notes for a session.
struct StructuredNotes: Identifiable, Codable, Sendable {
    let id: UUID
    /// Overall title for the notes
    let title: String
    /// Brief summary of the session
    let summary: String
    /// Ordered sections of content
    let sections: [NoteSection]
    /// Key takeaways / highlights
    let keyTakeaways: [String]
    /// When the notes were generated
    let generatedAt: Date
    /// Which LLM model produced these notes
    let modelUsed: String

    init(
        id: UUID = UUID(),
        title: String = "Untitled Notes",
        summary: String = "",
        sections: [NoteSection] = [],
        keyTakeaways: [String] = [],
        generatedAt: Date = Date(),
        modelUsed: String = NoteVConfig.NoteGeneration.llmModel
    ) {
        self.id = id
        self.title = title
        self.summary = summary
        self.sections = sections
        self.keyTakeaways = keyTakeaways
        self.generatedAt = generatedAt
        self.modelUsed = modelUsed
    }
}
