import Foundation

// MARK: - NoteImage

/// An image referenced within the generated notes.
struct NoteImage: Identifiable, Codable, Sendable {
    let id: UUID
    /// Filename of the image (references a stored frame)
    let filename: String
    /// Caption generated by the LLM
    let caption: String
    /// Timestamp in the session where this image was captured
    let timestamp: TimeInterval

    init(
        id: UUID = UUID(),
        filename: String,
        caption: String = "",
        timestamp: TimeInterval = 0
    ) {
        self.id = id
        self.filename = filename
        self.caption = caption
        self.timestamp = timestamp
    }
}

// MARK: - NoteSection

/// A section within the structured notes.
struct NoteSection: Identifiable, Codable, Sendable {
    let id: UUID
    /// Section heading
    let title: String
    /// Markdown-formatted content
    let content: String
    /// Images referenced in this section
    let images: [NoteImage]
    /// Order index for display
    let order: Int
    /// Start time in seconds since session start (nil for legacy data)
    let startTime: TimeInterval?
    /// End time in seconds since session start (nil for legacy data)
    let endTime: TimeInterval?
    /// Whether this section covers bookmarked highlights
    let isBookmarkSection: Bool

    init(
        id: UUID = UUID(),
        title: String,
        content: String = "",
        images: [NoteImage] = [],
        order: Int = 0,
        startTime: TimeInterval? = nil,
        endTime: TimeInterval? = nil,
        isBookmarkSection: Bool = false
    ) {
        self.id = id
        self.title = title
        self.content = content
        self.images = images
        self.order = order
        self.startTime = startTime
        self.endTime = endTime
        self.isBookmarkSection = isBookmarkSection
    }
}

// MARK: - NoteSection Timeline Helpers

extension NoteSection {
    /// Effective start time: explicit value, or earliest image timestamp
    var effectiveStartTime: TimeInterval? {
        startTime ?? images.map(\.timestamp).filter { $0 > 0 }.min()
    }

    /// Effective end time: explicit value, or latest image timestamp
    var effectiveEndTime: TimeInterval? {
        endTime ?? images.map(\.timestamp).filter { $0 > 0 }.max()
    }

    /// Formatted time range string (e.g., "12:30 - 15:45")
    var formattedTimeRange: String? {
        guard let start = effectiveStartTime else { return nil }
        let end = effectiveEndTime ?? start
        return "\(NoteSection.formatTime(start)) - \(NoteSection.formatTime(end))"
    }

    private static func formatTime(_ seconds: TimeInterval) -> String {
        let mins = Int(seconds) / 60
        let secs = Int(seconds) % 60
        return String(format: "%02d:%02d", mins, secs)
    }
}

// MARK: - StructuredNotes

/// The final AI-generated notes for a session.
struct StructuredNotes: Identifiable, Codable, Sendable {
    let id: UUID
    /// Overall title for the notes
    let title: String
    /// Brief summary of the session
    let summary: String
    /// Ordered sections of content
    let sections: [NoteSection]
    /// Key takeaways / highlights
    let keyTakeaways: [String]
    /// When the notes were generated
    let generatedAt: Date
    /// Which LLM model produced these notes
    let modelUsed: String

    init(
        id: UUID = UUID(),
        title: String = "Untitled Notes",
        summary: String = "",
        sections: [NoteSection] = [],
        keyTakeaways: [String] = [],
        generatedAt: Date = Date(),
        modelUsed: String = NoteVConfig.NoteGeneration.llmModel
    ) {
        self.id = id
        self.title = title
        self.summary = summary
        self.sections = sections
        self.keyTakeaways = keyTakeaways
        self.generatedAt = generatedAt
        self.modelUsed = modelUsed
    }
}
